### ISSUE TITLE
Filter value does not allow value to be zero (0)

### ISSUE THREAD

**Issue by soderluk** [nordsoftware/lumen-search#1]
Check is now if (empty($value)) throw exception. Should be strlen === 0 or something like that.

**Comment by cniska** [comment]
Could you be a bit more specific and tell me in which file this should be changed. Thanks!

**Comment by soderluk** [comment]
https://github.com/nordsoftware/lumen-search/blob/master/src/Filter.php#L131

But this issue has already been addressed.
